<a href="https://colab.research.google.com/github/rohitdanda/DeepLearning_DataSets/blob/master/MNIST_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First and fore most thing is to import data set from Keras 

In [3]:
from keras.datasets import mnist

(X_train,X_test),(y_train,y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


No new have the data but the shape of the train dataset dont have color change we need to reshape it to have it 

In [0]:
X_train = X_train.reshape(60000,28,28,1)

In [0]:
y_train = y_train.reshape(10000,28,28,1)

Now we have train data set now we need change the test data set to one hot encoding as it is human read

In [0]:
from keras.utils.np_utils import to_categorical

X_cat_test = to_categorical(X_test,10)
y_cat_test = to_categorical(y_test,10)

Now we need to normalize the pixel point between 0 and 1 instead of 0 to 255

In [0]:
X_train = X_train/X_train.max()
y_train = y_train/y_train.max()

Now all our datacleaning was done now we need create model and layers to it


In [19]:
from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPool2D,Flatten

model = Sequential()
model.add(Conv2D(filters=32,kernel_size=(4,4),activation='relu'))
model.add(MaxPool2D(pool_size=(4,4)))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [20]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [21]:
model.fit(X_train,X_test,epochs=5,verbose=2)





Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/5





 - 21s - loss: 0.1685 - acc: 0.9502
Epoch 2/5
 - 6s - loss: 0.0592 - acc: 0.9815
Epoch 3/5
 - 6s - loss: 0.0418 - acc: 0.9867
Epoch 4/5
 - 6s - loss: 0.0312 - acc: 0.9901
Epoch 5/5
 - 6s - loss: 0.0250 - acc: 0.9924


In [22]:
model.evaluate(y_train,y_test)

10000/10000 [==============================] - 1s 53us/step


[0.03362406979714287, 0.9893]

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
prediction = model.predict_classes(y_train,verbose=1)

10000/10000 [==============================] - 0s 43us/step


In [26]:
confusion = confusion_matrix(y_test,prediction)
print(confusion)

[[ 976    0    0    1    0    0    1    0    1    1]
 [   0 1132    0    2    0    0    0    0    1    0]
 [   0    0 1024    1    2    0    0    2    3    0]
 [   0    0    1 1006    0    0    0    0    2    1]
 [   0    0    0    0  968    0    1    0    3   10]
 [   2    0    0    6    0  878    1    0    1    4]
 [   5    2    0    0    1    2  944    0    4    0]
 [   0    4   10    1    0    0    0 1002    2    9]
 [   4    0    2    1    0    1    0    0  962    4]
 [   0    0    0    3    2    0    0    0    3 1001]]


In [28]:
classficationnn = classification_report(y_test,prediction)
print(classficationnn)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.99      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      1.00      0.99      1010
           4       0.99      0.99      0.99       982
           5       1.00      0.98      0.99       892
           6       1.00      0.99      0.99       958
           7       1.00      0.97      0.99      1028
           8       0.98      0.99      0.98       974
           9       0.97      0.99      0.98      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

